/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface": "#fef9f1",
        "background": "#fef9f1",
        "error-container": "#ffdad6",
        "on-surface": "#1d1c17",
        "on-tertiary": "#ffffff",
        "secondary-container": "#ffae89",
        "on-surface-variant": "#4d4540",
        "on-tertiary-container": "#b28156",
        "surface-container-high": "#ece8e0",
        "surface-container": "#f2ede5",
        "tertiary-fixed-dim": "#f4bb8b",
        "on-secondary-fixed": "#351000",
        "secondary-fixed": "#ffdbcc",
        "tertiary": "#1c0b00",
        "on-primary-container": "#938984",
        "on-tertiary-fixed-variant": "#643e19",
        "primary-fixed": "#ece0da",
        "outline-variant": "#d0c4bd",
        "secondary-fixed-dim": "#ffb695",
        "primary-container": "#29231f",
        "primary": "#130e0a",
        "on-background": "#1d1c17",
        "outline": "#7f756f",
        "inverse-surface": "#32302b",
        "surface-container-highest": "#e7e2da",
        "surface-bright": "#fef9f1",
        "on-primary-fixed-variant": "#4d4541",
        "on-primary-fixed": "#201a17",
        "on-secondary-container": "#793f22",
        "surface-variant": "#e7e2da",
        "surface-container-low": "#f8f3eb",
        "on-error": "#ffffff",
        "surface-tint": "#655d58",
        "inverse-on-surface": "#f5f0e8",
        "secondary": "#8c4e30",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#2e1500",
        "surface-dim": "#ded9d2",
        "tertiary-fixed": "#ffdcc1",
        "tertiary-container": "#3a1d00",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#d0c4be",
        "on-secondary": "#ffffff",
        "inverse-primary": "#d0c4be"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.375rem",
        "space-sm": "0.75rem",
        "space-md": "1.5rem",
        "space-lg": "2.5rem",
        "space-xl": "4rem",
        "space-2xl": "6rem",
        "margin": "4rem",
        "margin-md": "2.5rem",
        "margin-sm": "1.5rem",
        "gutter": "2rem",
        "gutter-sm": "1rem"
      },
      fontFamily: {
        "body-sm": ["Manrope", "sans-serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
        "display-hero": ["'Playfair Display'", "serif"],
        "display-hero-mobile": ["'Playfair Display'", "serif"],
        "title-md": ["Manrope", "sans-serif"],
        "headline-md-mobile": ["'Playfair Display'", "serif"],
        "label-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["'Playfair Display'", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        sans: ["Manrope", "sans-serif"],
        serif: ["'Playfair Display'", "serif"]
      },
      fontSize: {
        "body-sm": ["0.875rem", { lineHeight: "1.375rem", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-lg": ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.015em", fontWeight: "400" }],
        "display-hero": ["4.5rem", { lineHeight: "5rem", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-hero-mobile": ["2.75rem", { lineHeight: "3.25rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "title-md": ["1.125rem", { lineHeight: "1.625rem", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md-mobile": ["1.625rem", { lineHeight: "2.125rem", letterSpacing: "0", fontWeight: "400" }],
        "label-lg": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-md": ["1rem", { lineHeight: "1.625rem", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-sm": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.12em", fontWeight: "500" }],
        "label-md": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg-mobile": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-lg": ["1.125rem", { lineHeight: "1.875rem", letterSpacing: "0", fontWeight: "400" }],
        "headline-sm": ["1.5rem", { lineHeight: "2rem", letterSpacing: "0", fontWeight: "500" }]
      }
    }
  },
  plugins: []
}
